### ISSUE TITLE
How to properly delete an entity

### ISSUE THREAD

**Issue by tVoss** [r-lyeh/kult#1]
So this library seems great, super lightweight and has all the functionality one could need. Although it seems to be powered mostly by magic. I can't really tell how to delete an entity (e.g. if an enemy dies, an item is picked up, etc.). There doesn't seem to be a deconstructor on entity, so taking it out of scope doesn't seem like the solution. The only way I see is to remove all the components from an entity, but then they empty entity still sits in the map in kult.hpp.

Both those seems wrong. Is there something I'm missing with how to discard entities?

**Comment by tVoss** [comment]
After stepping away for a bit and looking at the code again, I can confirm that this is magic, but now I understand all the magic. The set of entities is actually a particular set for each component, whenever a component is added, the entity is added to the set and that's how things are kept track of.

So it seems the proper way to delete an entity is to go through all the components with `components()` and then call `del()` on each of them with the entity. The exact way to do this I'm not very sure of, but I'll tinker around with it. And advice / suggestions would be very useful.

**Comment by r-lyeh-archived** [comment]
Yes, sorry for the confusion. Kult is certainly one of the most cryptic, unreadable libraries that I've ever written. 
What is worse, Kult supports two undocumented APIs (`add<component_t>(id)` vs `component[entity]`).

There is no map that holds a record of the entity ID, so it should be fair to purge components.
You probably want to use `kult::purge(entity);` to iterate (and remove) all attached components.

**Comment by tVoss** [comment]
Ah okay that makes sense. Last question is if there is a way to get all the current entities (or simply purge all the entities as that's what I'm trying to do with all of them)

**Comment by r-lyeh-archived** [comment]
I've just added a new `kult::entities();` function that returns the current set of alive entities.
Hope it helps.

**Comment by tVoss** [comment]
Yes, thank you

**Comment by r-lyeh-archived** [comment]
Np, if you have any other suggestions, they're welcome.
Out of curiosity, are you using the `add<component_t>(id);` or `entity[component]` syntax?

**Comment by tVoss** [comment]
I'm a much bigger fan of the entity[component] syntax, it's much cleaner looking.
